import { StyleSheet } from "react-native";

const MyStylesheet = StyleSheet.create({
  bookListView: {
    // flex: 15,
    // alignItems: "center",
    // alignSelf: "stretch",
    // marginBottom: 10,
    // justifyContent: "flex-start",
    // borderRadius: 10,
    alignSelf: "stretch",
    justifyContent: "center",
  },
  dropdownStyle: {
    height: 150,
    backgroundColor: "#FFF",
  },
  boxStyle: {
    borderColor: "gray",
    borderWidth: 0,
    borderBottomWidth: 1,
    borderRadius: 0,
  },
  input: {
    borderColor: "gray",
    borderBottomWidth: 1,
    paddingHorizontal: 20,
    paddingVertical:5
    // flex: 1,
    // marginVertical: 5,
  },
  bookListItemTitleText: {
    fontSize: 25,
  },
  bookListItemTitle: {
    // flex: 5,
    // marginVertical: 2,
    padding: 2,
    alignItems: "flex-start",
    alignSelf: "stretch",
    justifyContent: "center",
    flexDirection: "column",
  },
  bookListItemOp: {
    // flex: 3,
    flexDirection: "row",
    justifyContent: "space-between",
    alignSelf: "stretch",
  },
  bookListItemIconsGroup: {
    // marginVertical: 2,
    padding: 2,
    alignSelf: "flex-end",
    flexDirection: "row",
  },
  bookListItemLang: {
    // marginVertical: 2,
    padding: 5,
    alignSelf: "flex-start",
  },
  bookListItem: {
    height: 120,
    // marginVertical: 5,
    // marginHorizontal: 5,
    padding: 2,
    color: "#000",
    flexDirection: "column",
    borderBottomWidth: 2,
    alignItems: "center",
    alignSelf: "stretch",
    justifyContent: "center",
    display: "flex",
    // borderRadius: 10,
  },
  bookListButtonArea: {
    // flex: 1,
    // marginVertical: 5,
    // alignItems: "center",
    // justifyContent: "space-around",
    display: "flex",
    flexDirection: "row",
    // alignSelf: "stretch",
  },
  bookListButton: {
    // flex: 1,
    // marginHorizontal: 5,
    margin: 5,
    color: "#000",
    borderWidth: 2,
    alignItems: "center",
    alignSelf: "stretch",
    justifyContent: "center",
    borderRadius: 10,
  },
  container: {
    // flex: 1,
    paddingTop: 5,
    padding: 15,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    display: "flex",
  },
  hints: {
    // flex: 2,
    fontSize: 20,
    textAlign: "left",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    marginBottom: 5,
  },
  text: {
    fontSize: 20,
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  view: {
    // flex: 10,
    alignItems: "center",
    justifyContent: "space-between",
    display: "flex",
    alignSelf: "stretch",
  },
  app_title: {
    // flex: 2,
    fontSize: 60,
    color: "#000",
    textAlign: "left",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  button: {
    // flex: 1,
    // marginVertical: 15,
    margin: 5,
    color: "#000",
    borderWidth: 2,
    alignItems: "center",
    alignSelf: "stretch",
    justifyContent: "center",
    borderRadius: 10,
  },
});

export default MyStylesheet;
