CREATE TABLE IF NOT EXISTS WORDS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    WORDSBOOK_ID INTEGER NOT NULL,
    WORDS_TEXT CHAR(50) NOT NULL,
    WORDS_TEXT_TRANSLATED CHAR(50) NOT NULL,
    DES CHAR(50) NULL,
    FOREIGN KEY (WORDSBOOK_ID) REFERENCES WORDSBOOKS(ID)
);
CREATE TABLE IF NOT EXISTS WORDSBOOKS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    WORDSBOOKS_NAME CHAR(50) NOT NULL,
    LANG_ID INTEGER NOT NULL,
    FOREIGN KEY (LANG_ID) REFERENCES LANG(ID)
);
CREATE TABLE IF NOT EXISTS LANG(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LANG_CODE CHAR(50) NOT NULL,
    LANG_DISPLAY_NAME CHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS SCOREBOARD(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CREATE_DTM DATETIME NOT NULL,
    WORDSBOOK_ID INTEGER NOT NULL,
    SCORE INTEGER NOT NULL,
    FOREIGN KEY (WORDSBOOK_ID) REFERENCES WORDSBOOKS(ID)
);

INSERT OR REPLACE INTO LANG (LANG_CODE, LANG_DISPLAY_NAME) VALUES ('en-US','ENGLISH (UNITED STATES)');
INSERT OR REPLACE INTO LANG (LANG_CODE, LANG_DISPLAY_NAME) VALUES ('zh-CN','CHINESE (SIMPLIFIED)');
INSERT OR REPLACE INTO LANG (LANG_CODE, LANG_DISPLAY_NAME) VALUES ('zh-TW','CHINESE (TRADITIONAL)');
INSERT OR REPLACE INTO LANG (LANG_CODE, LANG_DISPLAY_NAME) VALUES ('ja-JP','JAPANESE (JAPAN)');

INSERT OR REPLACE INTO WORDSBOOKS (WORDSBOOKS_NAME, LANG_ID ) VALUES ('心, 夏目漱石', 4);
INSERT OR REPLACE INTO WORDSBOOKS (WORDSBOOKS_NAME, LANG_ID ) VALUES ('蜘蛛の糸, 芥川龍之介', 4);
INSERT OR REPLACE INTO WORDSBOOKS (WORDSBOOKS_NAME, LANG_ID ) VALUES ('おれは二十面相だ, 江戸川 乱歩', 4);
INSERT OR REPLACE INTO WORDSBOOKS (WORDSBOOKS_NAME, LANG_ID ) VALUES ('1984, George Orwell', 1);
INSERT OR REPLACE INTO WORDSBOOKS (WORDSBOOKS_NAME, LANG_ID ) VALUES ('MS. Found in a Bottle, Edgar Allan Poe', 1);

INSERT OR REPLACE INTO WORDS 
(WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) 
VALUES (1, '貴方', 'あなた ANATA 您（女性常用）', '夫妻、情侶之間');
INSERT OR REPLACE INTO WORDS 
(WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) 
VALUES (1, '心', 'こころ kokoro 心', ' - ');
INSERT OR REPLACE INTO WORDS 
(WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) 
VALUES (1, '君', 'きみ kimi 你（同輩/晚輩）', ' - ');
INSERT OR REPLACE INTO WORDS 
(WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) 
VALUES (4, 'Mediterranean', '地中海', '地理');



