import * as SQLite from "expo-sqlite";

export const DATABASE_NAME = "db_v1.db";

const clear_db = `
DELETE FROM WORDS;
DELETE FROM WORDSBOOKS;
DELETE FROM LANG;
DROP TABLE IF EXISTS WORDS;
DROP TABLE IF EXISTS WORDSBOOKS;
DROP TABLE IF EXISTS LANG;
DROP TABLE IF EXISTS SCOREBOARD;
`;

const demo_db = `
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (1, 'en-US','ENGLISH (UNITED STATES)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (2, 'zh-CN','CHINESE (SIMPLIFIED)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (3, 'zh-TW','CHINESE (TRADITIONAL)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (4, 'ja-JP','JAPANESE (JAPAN)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (5, 'en-GB','English (United Kingdom)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (6, 'ko-KR','Korean (South Korea)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (7, 'es-ES','Spanish (Spain)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (8, 'es-MX','Spanish (Mexico)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (9, 'fr-FR','French (France)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (10, 'fr-CA','French (Canada)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (11, 'de-DE','German (Germany)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (12, 'de-AT','German (Austria)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (13, 'it-IT','Italian (Italy)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (14, 'pt-BR','Portuguese (Brazil)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (15, 'pt-PT','Portuguese (Portugal)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (16, 'ru-RU','Russian (Russia)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (17, 'ar-SA','Arabic (Saudi Arabia)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (18, 'hi-IN','Hindi (India)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (19, 'vi-VN','Vietnamese (Vietnam)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (20, 'th-TH','Thai (Thailand)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (21, 'id-ID','Indonesian (Indonesia)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (22, 'ms-MY','Malay (Malaysia)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (23, 'tr-TR','Turkish (Turkey)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (24, 'nl-NL','Dutch (Netherlands)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (25, 'sv-SE','Swedish (Sweden)');
INSERT OR IGNORE INTO LANG (ID, LANG_CODE, LANG_DISPLAY_NAME) VALUES (26, 'Others','Others Languages');

INSERT OR IGNORE INTO WORDSBOOKS (ID, WORDSBOOKS_NAME, LANG_ID ) VALUES (1, '心, 夏目漱石', 4);
INSERT OR IGNORE INTO WORDSBOOKS (ID, WORDSBOOKS_NAME, LANG_ID ) VALUES (2, '1984, George Orwell', 1);
INSERT OR IGNORE INTO WORDSBOOKS (ID, WORDSBOOKS_NAME, LANG_ID ) VALUES (3, 'ごじゅうおん 五十音, 「明覺」僧侶', 4);

INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (1, 1, '貴方', 'あなた ANATA 您（女性常用）', '夫妻、情侶之間 (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (2, 1, '心', 'こころ kokoro 心', ' - (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (3, 1, '君', 'きみ kimi 你（同輩/晚輩）', ' - (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (4, 1, '私', 'わたくし 我', ' - (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (5, 1, '卒業', 'そつぎょう sotsugyou 畢業', ' - (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (6, 1, '手紙', 'てがみ tegami 信', ' - (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (7, 1, '親類', 'しんるい sinnrui 親戚', ' - (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (8, 1, '端書/葉書', 'はがき hagaki 明信片', ' - (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (9, 1, '見逃し', 'みのがし minogasi 看漏／錯過', ' - (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (10, 2, 'Comrades!', '同志們！', '又可解戰友，伙伴 (Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (11, 3, 'あ/ア', 'a', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (12, 3, 'い/イ', 'i', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (13, 3, 'う/ウ', 'u', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (14, 3, 'え/エ', 'e', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (15, 3, 'お/オ', 'o', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (16, 3, 'か/カ', 'ka', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (17, 3, 'け/キ', 'ki', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (18, 3, 'く/ク', 'ku', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (19, 3, 'け/キ', 'ke', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (20, 3, 'こ/コ', 'ko', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (21, 3, 'さ/サ', 'sa', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (22, 3, 'し/シ', 'si', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (23, 3, 'す/ス', 'su', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (24, 3, 'せ/セ', 'se', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (25, 3, 'そ/ソ', 'so', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (26, 3, 'た/タ', 'ta', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (27, 3, 'ち/テ', 'chi', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (28, 3, 'つ/ツ', 'tsu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (29, 3, 'て/テ', 'te', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (30, 3, 'と/ト', 'to', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (31, 3, 'な/ナ', 'na', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (32, 3, 'に/ニ', 'ni', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (33, 3, 'ぬ/ヌ', 'no', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (34, 3, 'ね/ネ', 'ne', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (35, 3, 'の/ノ', 'no', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (36, 3, 'は/ハ', 'ha', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (37, 3, 'ひ/ヒ', 'hi', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (38, 3, 'ふ/フ', 'fu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (39, 3, 'へ/ヘ', 'he', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (40, 3, 'ほ/ホ', 'ho', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (41, 3, 'ま/マ', 'ma', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (42, 3, 'み/ミ', 'mi', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (43, 3, 'む/ム', 'mu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (44, 3, 'め/メ', 'me', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (45, 3, 'も/モ', 'mo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (46, 3, 'や/ヤ', 'ya', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (47, 3, 'ゆ/ユ', 'yu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (48, 3, 'よ/ヨ', 'yo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (49, 3, 'ら/ラ', 'ra', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (50, 3, 'り/リ', 'ri', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (51, 3, 'る/ル', 'ru', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (52, 3, 'れ/レ', 're', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (53, 3, 'ろ/ロ', 'ro', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (54, 3, 'わ/ワ', 'wa', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (55, 3, 'を/ヲ', 'wo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (56, 3, 'ん/ン', 'nn', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (57, 3, 'きゃ/キャ', 'kya', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (58, 3, 'きゅ/キュ', 'kyu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (59, 3, 'きょ/キョ', 'kyo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (60, 3, 'しゃ/シャ', 'sha', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (61, 3, 'しゅ/シュ', 'shu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (62, 3, 'しょ/ショ', 'sho', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (63, 3, 'ちゃ/チャ', 'cha', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (64, 3, 'ちゅ/チュ', 'chu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (65, 3, 'ちょ/チョ', 'cho', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (66, 3, 'にゃ/ニャ', 'nya', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (67, 3, 'にゅ/ニュ', 'nyu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (68, 3, 'にょ/ニョ', 'nyo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (69, 3, 'ひゃ/ヒャ', 'hya', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (70, 3, 'ひゅ/ヒュ', 'hyu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (71, 3, 'ひょ/ヒョ', 'hyo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (72, 3, 'みゃ/ミャ', 'mya', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (73, 3, 'みゅ/ミュ', 'myu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (74, 3, 'みょ/ミョ', 'myo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (75, 3, 'りゃ/リャ', 'rya', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (76, 3, 'りゅ/リュ', 'ryu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (77, 3, 'りょ/リョ', 'ryo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (78, 3, 'が/ガ', 'ga', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (79, 3, 'ぎ/ギ', 'gi', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (80, 3, 'ぐ/グ', 'gu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (81, 3, 'げ/ゲ', 'ge', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (82, 3, 'ご/ゴ', 'go', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (83, 3, 'ざ/ザ', 'za', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (84, 3, 'じ/ジ', 'ji', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (85, 3, 'ず/ズ', 'zu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (86, 3, 'ぜ/ゼ', 'ze', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (87, 3, 'ぞ/ゾ', 'zo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (88, 3, 'だ/ダ', 'da', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (89, 3, 'じ/ジ', 'di', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (90, 3, 'ず/ズ', 'du', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (91, 3, 'で/デ', 'de', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (92, 3, 'ど/ド', 'do', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (93, 3, 'ば/バ', 'ba', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (94, 3, 'び/ビ', 'be', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (95, 3, 'ぶ/ブ', 'bu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (96, 3, 'べ/ベ', 'be', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (97, 3, 'ぼ/ボ', 'bo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (98, 3, 'ぱ/パ', 'pa', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (99, 3, 'ぴ/ピ', 'pi', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (100, 3, 'ぷ/プ', 'pu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (101, 3, 'ぺ/ペ', 'pe', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (102, 3, 'ぽ/ポ', 'po', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (103, 3, 'ぎゃ/ギャ', 'gya', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (104, 3, 'ぎゅ/ギュ', 'gyu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (105, 3, 'ぎょ/ギョ', 'gyo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (106, 3, 'じゃ/ジャ', 'ja', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (107, 3, 'じゅ/ジュ', 'ju', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (108, 3, 'じょ/ジョ', 'jo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (109, 3, 'びゃ/ビャ', 'bya', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (110, 3, 'びゅ/ビュ', 'byu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (111, 3, 'びょ/ビョ', 'byo', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (112, 3, 'ぴゃ/ピャ', 'pya', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (113, 3, 'ぴゅ/ピュ', 'pyu', '(Testing word, delete is not allow)');
INSERT OR IGNORE INTO WORDS (ID, WORDSBOOK_ID, WORDS_TEXT, WORDS_TEXT_TRANSLATED, DES) VALUES (114, 3, 'ぴょ/ピョ', 'pyo', '(Testing word, delete is not allow)');
`;

export const initDatabase = async (): Promise<SQLite.SQLiteDatabase> => {
  const db = await SQLite.openDatabaseAsync(DATABASE_NAME);

  // Optional: Enable WAL mode and foreign keys for performance/relations

  await db.execAsync(
    // clear_db + //uncomment this code if u want clean all data on app start
    `
CREATE TABLE IF NOT EXISTS WORDS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    WORDSBOOK_ID INTEGER NOT NULL,
    WORDS_TEXT CHAR(50) NOT NULL,
    WORDS_TEXT_TRANSLATED CHAR(50) NOT NULL,
    DES CHAR(50) NULL,
    FOREIGN KEY (WORDSBOOK_ID) REFERENCES WORDSBOOKS(ID)
);
CREATE TABLE IF NOT EXISTS WORDSBOOKS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    WORDSBOOKS_NAME CHAR(50) NOT NULL,
    LANG_ID INTEGER NOT NULL,
    FOREIGN KEY (LANG_ID) REFERENCES LANG(ID)
);
CREATE TABLE IF NOT EXISTS LANG(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LANG_CODE CHAR(50) NOT NULL,
    LANG_DISPLAY_NAME CHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS SCOREBOARD(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CREATE_DTM DATETIME NOT NULL,
    WORDSBOOK_ID INTEGER NOT NULL,
    SCORE INTEGER NOT NULL,
    FOREIGN KEY (WORDSBOOK_ID) REFERENCES WORDSBOOKS(ID)
);
` + demo_db
  );
  console.log("Database initialized");
  return db;
};

export default { initDatabase, DATABASE_NAME };
